# Generated by Django 4.1.5 on 2023-04-29 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=35, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=15, verbose_name='telefono')),
                ('nacionalidad', models.CharField(max_length=25, verbose_name='nacionalidad')),
                ('correo', models.CharField(max_length=50, verbose_name='correo')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordene',
            fields=[
                ('idOrden', models.BigAutoField(primary_key=True, serialize=False, verbose_name='num_orden')),
                ('estado', models.CharField(max_length=10, verbose_name='estado')),
                ('demension', models.CharField(max_length=40, verbose_name='dimension')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cliente')),
            ],
        ),
    ]
