# Generated by Django 4.1.5 on 2023-04-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='ide'),
        ),
    ]
