# Generated by Django 4.1.5 on 2023-04-29 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_cliente_identificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idOrden', models.BigAutoField(primary_key=True, serialize=False, verbose_name='num_orden')),
                ('estado', models.CharField(default='Solicitada', max_length=10, verbose_name='estado')),
                ('demension', models.CharField(max_length=40, verbose_name='dimension')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Ordene',
        ),
    ]
