# Generated by Django 4.1.5 on 2023-04-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_orden_delete_ordene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='demension',
        ),
    ]
