# Generated by Django 4.1.5 on 2023-04-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_remove_orden_demension'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='detalle',
            field=models.CharField(max_length=15, null=True, verbose_name='detalle'),
        ),
    ]
